name: dooadex_http
description: A useful src.http package.
version: 0.0.1
repository:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  dooadex_error_handler: ^0.0.3
  dooadex_logger: ^0.0.2
  dooadex_constants: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: